### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by deadman96385** [sjvc/Home-Assistant-Launcher#2]
Using a local home assistant install, the tablet is hooked up to the same wifi. If I go to the ip address in chrome it works but it doesn't do anything in the app.

![screenshot_20180302-092707](https://user-images.githubusercontent.com/2042793/36878908-1cd9df4e-1dfc-11e8-8eeb-2649a2772c49.png)

**Comment by sjvc** [comment]
Try writing the protocol (http:// or https://) and ensure you touched the "done" button in keyboard.

**Comment by deadman96385** [comment]
http:// fixed it thanks

**Comment by 12nick12** [comment]
Mine doesn't seem to work. https://site.com:38123. My server is using a nginx reverse proxy bc google TTS doesn't work with SSL on the hass server.

**Comment by 12nick12** [comment]
That's not the actually url, but I have the https:// and :38123 defined. If I copy the url into chrome it works fine.
