### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vlaraort** [sjvc/Home-Assistant-Launcher#4]
Hi! Your proyect is exactly what I was looking for! Thank you!

One suggestion. A really great improvement would be to use different urls if you are connected to a defined wifi. There are a lot of people (including me), who has to use local IP from their home, and a DNS from outside.

If you want, I can try to help, but my main skill is JS, not Android.

Regards

**Comment by sjvc** [comment]
Hi! Thanks for your feature request. 

I planned to do it when I created this project (my router does not have NAT loopback, so I need to use local IP from my home, and external IP from outside). But I realized there is a better, and easier approach. You just have to install dnsmasq on your Raspberry Pi, so it will resolve your domain name to your local ip, inside your local network. Just install dnsmasq, configure it, and set Raspberry Pi IP as your DNS server in your mobile device, for your WiFi: https://community.home-assistant.io/t/letsencrypt-solution-starting-from-hassbian-1-1-image/15848/8

Let me know if you need help with this. I'm using it, and it works.
