### ISSUE TITLE
Feature Request: fix oauth support

### ISSUE THREAD

**Issue by iliketoprogram14** [sjvc/Home-Assistant-Launcher#7]
I use oauth_proxy in front of my HASS installation. When using the launcher, I'm redirected to an error page saying embedded browsers (ie, webviews) do not support oaith requests. Here's a link to the page describing the [deprecation](https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/). 

One quick and dirty way around this is to set the user agent to something else, such as the Chrome desktop or mobile browser. The proper solutions seem like a lot more work, such as switching to Chrome Custom Tabs or adding Oaith support yourself.

**Comment by sjvc** [comment]
This project is a hobby, so I don't have enough free time to add all your requests. But, as this project is open source, anyone can add their own features.

**Comment by iliketoprogram14** [comment]
Would you mind if I change the user agent then?
