### ISSUE TITLE
Feature request: Support Home Assistant notifications

### ISSUE THREAD

**Issue by kstolk** [sjvc/Home-Assistant-Launcher#8]
This will make many android users happy I guess. I currently have an Iphone with the Home Assistant app and I receive push notifications trough that app. My GF has a Android phone and I need to install an extra app to support push notifications for her, would be better if this app can support it.

**Comment by sjvc** [comment]
This project is a hobby, so I don't have enough free time to add all your requests. But, as this project is open source, anyone can add their own features.
