### ISSUE TITLE
Top bar has a static color

### ISSUE THREAD

**Issue by ghost** [sjvc/Home-Assistant-Launcher#9]
As a home assistant user I've customized the whole theme. When I use this application (vs the web app) the top bar has a flashy blue (default) home assistant theme even after setting the theme to something else.

Is it possible to either:
- Manually pick a color within the app for the top bar
- Inherit the color of the applied theme in home assistant

**Comment by sjvc** [comment]
This project is a hobby, so I don't have enough free time to add all your requests. But, as this project is open source, anyone can add their own features.
